before_script:
  - vagga _init_storage_dir --allow-multiple swindonJS
stages:
  - build
  - test
  - cleanup
build:
  stage: build
  script:
  - vagga build
test:
  stage: test
  script:
  - vagga test